projects:
  GitHub API:
    schema:
      - https://api.github.com/graphql:
          headers:
            Authorization: Bearer ${GITHUB_TOKEN}
    include:
      - src/api/github/*.ts
      - src/api/github/queries/*.graphql
