# SPDX-FileCopyrightText: 2024 AFCMS <afcm.contact@gmail.com>
# SPDX-License-Identifier: CC0-1.0

projects:
  GitHub API:
    schema:
      - https://api.github.com/graphql:
          headers:
            Authorization: Bearer ${DEVPET_GITHUB_TOKEN}
    include:
      - src/api/github/*.ts
      - src/api/github/queries/*.graphql
